// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Form.tsx": $Form,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
